server:
  port: 8570
---
spring:
  application:
    name: freesia-admin
    admin:
      enabled: true
---
spring:
  boot:
    admin:
      server:
        enabled: true
      #      context-path: /spring-admin
      ui:
        brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>Freesia Spring Boot Admin</span>"
      client:
        enabled: false
        url: http://localhost:8570
        instance:
          service-host-type: IP
          metadata:
            username: ${spring.boot.admin.client.username}
            userpassword: ${spring.boot.admin.client.password}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
---
spring:
  security:
    user:
      name: @monitor.username@
      password: @monitor.password@
---
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---
freesia:
  web:
    common:
      # 是否初始化系统配置
      init-sys-config: true
      # 是否初始化数据字典
      init-sys-dict: true
      # 是否初始化后端公钥
      init-secret-key: true
    tenant:
      enabled: true
      tenant-column: TENANT_ID
      ignore-table:
        - SYS_TENANT
        - SYS_USER
        - SYS_MENU
        - SYS_DEPT
        - SYS_ROLE
        - SYS_ROLE_MENU
        - SYS_ROLE_DEPT
        - SYS_TENANT_USER
        - SYS_USER_ROLE
        - SYS_DICT_KEY
        - SYS_DICT_VALUE
        - URL_CONFIG
        - SYS_CONFIG
        - SYS_OSS
        - SYS_OSS_CONFIG
        - DATESERIES
        - ACCOUNT_COST
        - ACCOUNT_COST_USER_ALLOC
        - ACCOUNT_BUDGET
        - ACCOUNT_REPORT
        - ACCOUNT_REPORT_STRATEGY
        - COMMON_ICON
        - COMMON_ICON_TEMPLATE_HEADER
        - COMMON_ICON_TEMPLATE_DETAIL
        - SYS_NOTICE
        - WORLD_CLOCK_CITY
        - WORLD_CLOCK_SUNRISE_SUNSET
        - COMMON_TODO
---
login.password:
  # 密码最大错误次数
  maxRetryCount: 5
  # 密码锁定时间（默认10分钟 Duration）
  lockTime: 10M
  # 初始化密码
  init-password: 123456
---
# 生成验证码
captcha:
  type: CALCULATE
  strategy: CIRCLE
  numberLength: 1
  charLength: 4
---
spring:
  messages:
    # 引入不同模块的i18n messages文件，逗号分隔
    basename: i18n/messages_account,i18n/messages_common,i18n/messages,i18n/messages_common_service
    encoding: UTF-8
---
# Sa-Token配置
sa-token:
  # 打印日志
  is-log: false
  # 打印彩色日志
  is-color-log: false
  # 启动不打印banner
  is-print: false
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期 设为一天 (必定过期) 单位: 秒
  timeout: 86400
  # 多端不同 token 有效期 可查看 USecurity.loginByDevice 方法自定义
  # token最低活跃时间 (指定时间无操作就过期) 单位: 秒
  active-timeout: 43200
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # token前缀
  token-prefix: "Bearer"
  # jwt秘钥
  jwt-secret-key: DoYouLikeWhatYouSee?
---
# security配置
security:
  # 排除路径
  excludes:
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
---
# 接口文档
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    # 添加该属性才能在刷新或重新打开标签时不会重置auth值
    persist-authorization: true
  info:
    title: Devilvan's Freesia Admin Document
    description: Freesia后台管理系统_接口文档
    license:
      name: APACHE LICENSE VERSION 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    version: '版本号: ${project.version}'
    termsOfService: 'http://localhost:${server.port}}'
    contact:
      name: Evad Devilvan
      email: evaddevilvan@outlook.com
      url: https://gitee.com/devilvan/freesia
  externalDocs:
    description: Git仓库地址
    url: https://gitee.com/devilvan/freesia
  components:
    # 鉴权方式配置
    security-schemes:
      apiKey:
        type: APIKEY
        in: HEADER
        name: ${sa-token.token-name}
      tenantId:
        type: APIKEY
        in: HEADER
        name: X-Tenant-Id
  group-configs:
    - group: 01. 登录、注册模块
      paths-to-match:
        - /api/sysLoginController/**
        - /api/sysRegistryController/**
    - group: 02. 用户模块
      paths-to-match: /api/sysUserController/**
    - group: 03. 角色模块
      paths-to-match: /api/sysRoleController/**
    - group: 04. 菜单模块
      paths-to-match: /api/sysMenuController/**
    - group: 05. 部门模块
      paths-to-match: /api/sysDeptController/**
    - group: 06. 字典模块
      paths-to-match: /api/sysDictController/**
    - group: 07. 操作日志模块
      paths-to-match: /api/sysSensitiveLogController/**
    - group: 08. 数据面板模块
      paths-to-match: /dashboard/**
    - group: 09. 基础服务模块
      paths-to-match: /common/**
    - group: 10. 租户模块
      paths-to-match: /api/sysTenantController/**
    - group: 11. 记账模块
      paths-to-match: /api/accountCostController/**
    - group: 12. 通用图标模块
      paths-to-match: /common/commonIcon*/**
# knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
gitee:
  commits:
    url: https://gitee.com/api/v5/repos/devilvan/freesia/commits
  oauth:
    url: https://gitee.com/oauth/token
    per-page: 20
---
xxl:
  job:
    admin:
      enabled: true
      ip: 127.0.0.1
      port: 8596
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。
      # 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://${xxl.job.admin.ip}:${xxl.job.admin.port}/xxl-job-admin
      # 执行器通讯TOKEN [选填]：非空时启用；
      accessToken: Wjw#Dhevilvan*578395%Bliss
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname:
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。
      #从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；
      # 地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 8598
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /logs/xxljob
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 7