project:
  version: @freesia.version@
---
spring:
  profiles:
    # 根据当前活跃环境指定对应的 application文件
    active: @profiles.active@
---
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/freesia?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&generateSimpleParameterMetadata=true&nullCatalogMeansCurrent=true
    username: root
    password: lklpos
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        enabled: true
        login-username: Devilvan
        login-password: 741258963hjkl
        reset-enable: false
        url-pattern: /druid/*
        # 设置白名单，不填则允许所有访问
        allow: localhost
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
---
spring:
  data:
    redis:
      repositories:
        enabled: false
---
spring:
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER
---
spring:
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 所有文件上传总大小
      max-request-size: 100MB
---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 最大活动数量
        max-active: 8
        # 当池耗尽时，在引发异常之前，连接分配应该阻塞的最长时间。使用负值可以无限期阻止。
        max-wait: -1
        # 最大闲置时间，单位：s
        max-idle: 500
        # 超时关闭时间
      shutdown-timeout: 0
---
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # 有p6spy了就可以不用你了
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
      generate_statistics: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          # 批量保存时重写SQL语句，每批1000条提交
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        # 定义JPA的SQL拦截，没有需要可以不创建
        session_factory:
          statement_inspector: com.freesia.interceptor.JpaDataPermissionInterceptor
# Mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: true
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  global-config:
    banner: false
    worker-id: ${random.int(1,31)}
    datacenter-id: ${random.int(1,31)}
    db-config:
      id-type: ASSIGN_ID
# 日志相关
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
# spring安全信息
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      enabled: true
      show-details: always
---
sse:
  enabled: false