<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>freesia-web</artifactId>
        <groupId>com.freesia</groupId>
        <version>1.3.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>freesia-web-app</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-web-account</artifactId>
            <version>${freesia.version}</version>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-web-icon</artifactId>
            <version>${freesia.version}</version>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-web-admin</artifactId>
            <version>${freesia.version}</version>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-web-framework</artifactId>
            <version>${freesia.version}</version>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-web-api</artifactId>
            <version>${freesia.version}</version>
        </dependency>
        <!-- 基础模块-->
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-oss</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-json</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-excel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-crypt</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-satoken</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-desensitization</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-net</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-doc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-idempotent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-sse</artifactId>
        </dependency>
        <dependency>
            <groupId>com.freesia</groupId>
            <artifactId>freesia-common-mail</artifactId>
        </dependency>
        <!--spring-test测试=-->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.7.0</version>
                <configuration>
                    <!-- 如果没有该配置，devtools不会生效 -->
                    <fork>true</fork>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.2</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <warName>${project.artifactId}</warName>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
