<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>freesia</artifactId>
        <groupId>com.freesia</groupId>
        <version>1.0.0</version>
    </parent>
    <artifactId>freesia-web</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0</version>
    <modules>
        <module>freesia-web-app</module>
        <module>freesia-web-api</module>
        <module>freesia-web-framework</module>
        <module>freesia-web-admin</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- Web模块-->
            <dependency>
                <groupId>com.freesia</groupId>
                <artifactId>freesia-web-api</artifactId>
                <version>${freesia.version}</version>
            </dependency>
            <dependency>
                <groupId>com.freesia</groupId>
                <artifactId>freesia-web-framework</artifactId>
                <version>${freesia.version}</version>
            </dependency>
            <dependency>
                <groupId>com.freesia</groupId>
                <artifactId>freesia-web-admin</artifactId>
                <version>${freesia.version}</version>
            </dependency>
            <!--基础模块-->
            <dependency>
                <groupId>com.freesia</groupId>
                <artifactId>freesia-common-api</artifactId>
                <version>${freesia.version}</version>
            </dependency>
            <dependency>
                <groupId>com.freesia</groupId>
                <artifactId>freesia-common-framework</artifactId>
                <version>${freesia.version}</version>
            </dependency>
            <dependency>
                <groupId>com.freesia</groupId>
                <artifactId>freesia-common-service</artifactId>
                <version>${freesia.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
