server:
  # \u53EA\u80FD\u9009\u62E98xxx\u7AEF\u53E3
  port: 8003
spring:
  application:
    ## \u6CE8\u518C\u670D\u52A1\u540D
    name: freesia-spring-admin
    admin:
      enabled: true
---
spring:
  boot:
    admin:
      context-path: /spring-admin
      client:
        enabled: true
        url: http://localhost:8003/spring-admin
        instance:
          metadata:
            username: ${spring.boot.admin.client.username}
            userpassword: ${spring.boot.admin.client.password}
        username: @monitor.username@
        password: @monitor.password@
management:
  endpoint:
    health:
      show-details: always